rate_limits:
  - domain: messaging
    descriptors:
      message_type: marketing
    rate_limit:
      unit: minute
      requests_per_unit: 5
  - domain: auth
    descriptors:
      auth_type: login
    rate_limit:
      unit: minute
      requests_per_unit: 5
